version: "3.8"

services:
    nginx:
       image: nginx:1.21-alpine
       container_name: layer-7-lb
       hostname: lb-layer-7
       ports:
        - 80:80
       networks:
        - lb-net 
       volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    
    app1:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app1
     container_name: app1
     networks:
        - lb-net
     ports:              
        - 8001:5000         
    app2:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app2
     container_name: app2
     networks:
        - lb-net
     ports:
        - 8002:5000
    
    app3:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app3
     container_name: app3
     networks:
        - lb-net
     ports:              
        - 8003:5000

    app4:
     build:
      context: ./app
      dockerfile: Dockerfile
     hostname: app4
     container_name: app4
     networks:
        - lb-net
     ports:              
        - 8004:5000
networks:
  lb-net:
    name: lb-net 
    driver: bridge


